// Generated by LiveScript 1.2.0
(function(){
  var hourMillis, dayMillis, msgCount, __callback, __usrIdx, _randomiseTimestamp, _createMessage, _randomMessages;
  hourMillis = 60 * 60 * 1000;
  dayMillis = 24 * hourMillis;
  msgCount = 0;
  __callback = null;
  __usrIdx = 1;
  _randomiseTimestamp = function(original){
    var dayShift, hourShift;
    dayShift = Math.floor(Math.random() * 4);
    hourShift = Math.floor(Math.random() * 8);
    return original - dayShift * dayMillis;
  };
  _createMessage = function(){
    var contacts, userCount, userIdx, user, msgId, timestamp;
    contacts = Stadium.HubRepository._people;
    userCount = contacts.length;
    userIdx = Math.floor(Math.random() * 2);
    user = contacts[userIdx];
    msgId = msgCount++;
    timestamp = Date.now();
    if (Math.random() > 0.66) {
      timestamp = _randomiseTimestamp(timestamp);
    }
    return {
      userIdentifier: user.identifier,
      author: user.name,
      message: "This is the content of message  " + msgId + ", " + user.name,
      id: "message-" + msgId,
      timeStamp: timestamp
    };
  };
  _randomMessages = function(num, cb){
    var i$, i, results$ = [];
    for (i$ = 1; i$ <= num; ++i$) {
      i = i$;
      results$.push(cb());
    }
    return results$;
  };
  module.exports = {
    CreateRandomMessage: _createMessage,
    RandomMessages: _randomMessages
  };
}).call(this);
