// Generated by LiveScript 1.2.0
(function(){
  var MxWithFullscreen, this$ = this;
  MxWithFullscreen = {
    toggleFullscreen: function(panel){
      if (panel.classList.contains('is-fullscreen')) {
        this$._dropFullscreen(panel);
      } else {
        this$._goFullscreen(panel);
      }
    },
    _goFullscreen: function(toFullscreen){
      var panels, vcl, i$, len$, panel, cl;
      panels = this$._participantPanels;
      vcl = this$.View.classList;
      for (i$ = 0, len$ = panels.length; i$ < len$; ++i$) {
        panel = panels[i$];
        cl = panel.classList;
        if (panel === toFullscreen) {
          if (cl.contains('is-rostered')) {
            cl.remove('is-rostered');
          }
          cl.add('is-fullscreen');
        } else {
          if (cl.contains('is-fullscreen')) {
            cl.remove('is-fullscreen');
          }
          cl.add('is-rostered');
        }
      }
      if (!vcl.contains('has-fullscreen')) {
        vcl.add('has-fullscreen');
      }
    },
    _dropFullscreen: function(){
      var i$, ref$, len$, classList;
      this$.View.classList.remove('has-fullscreen');
      for (i$ = 0, len$ = (ref$ = this$._participantPanels).length; i$ < len$; ++i$) {
        classList = ref$[i$].classList;
        classList.remove('is-fullscreen');
        classList.remove('is-rostered');
      }
    }
  };
  module.exports = {
    MxWithFullscreen: MxWithFullscreen
  };
}).call(this);
