// Generated by LiveScript 1.2.0
(function(){
  var _vid, _createVideoTag, RemoteVideo;
  _vid = 0;
  _createVideoTag = function(){
    var t;
    t = document.createElement('video');
    t.setAttribute('src', './videos/big_buck_bunny.webm');
    return t;
  };
  RemoteVideo = (function(){
    RemoteVideo.displayName = 'RemoteVideo';
    var prototype = RemoteVideo.prototype, constructor = RemoteVideo;
    function RemoteVideo(){
      this._starting = false;
      this._playing = false;
      this._videoTag = null;
      this._identifier = null;
      Object.defineProperties(this, {
        Playing: {
          value: false,
          writable: true,
          enumerable: true
        },
        Starting: {
          value: false,
          writable: true,
          enumerable: true
        },
        VideoTag: {
          get: function(){
            if (this._videoTag == null) {
              this._videoTag = _createVideoTag();
              this._identifier = this._videoTag.src;
            }
            return this._videoTag;
          },
          set: function(v){
            this._videoTag = v;
            this._identifier = this._videoTag.src;
          },
          enumerable: true
        },
        identifier: {
          value: "foo",
          enumerable: true,
          writable: true
        }
      });
    }
    return RemoteVideo;
  }());
  module.exports = {
    RemoteVideo: RemoteVideo
  };
}).call(this);
